# Definizione di una singola rete bridge
networks:
  app_network:
    driver: bridge

# Definizione dei volumi per persistere i dati
volumes:
  pihole_data:
  nginx_proxy_manager_data:
  nginx_proxy_manager_certs:

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Rome'
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_dns_listeningMode: 'all'
    networks:
      - app_network
    volumes:
      - 'pihole_data:/etc/pihole'

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8081:81"
    networks:
      - app_network
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_certs:/etc/letsencrypt