# Definizione di una singola rete bridge
networks:
  app_network:
    driver: bridge

# Definizione dei volumi per persistere i dati
volumes:
  pihole_data:
 
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Rome'
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_dns_listeningMode: 'all'
    networks:
      - app_network
    volumes:
      - 'pihole_data:/etc/pihole'
    restart: unless-stopped